### ISSUE TITLE
Apply Common Code Style to Networking

### ISSUE THREAD

**Issue by kyleyoung1121** [EECE3093C/team-wiitanks-godot-4-networking#6]
We are using GDScript style guide found here: https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html

Review existing files within the Networking repo and ensure that this code meets the common style guide

**Comment by watermelonslice** [comment]
this code is about to be so consistent in terms of style y'all aren't even ready for it

**Comment by watermelonslice** [comment]
Completed the move to static typing and style in accordance to the Godot style guide.

**Comment by watermelonslice** [comment]
Need to align file names and folder names to style guide

**Comment by watermelonslice** [comment]
finished, everything's consistent now
