### ISSUE TITLE
Create Issues for: Unit Testing within Networking

### ISSUE THREAD

**Issue by kyleyoung1121** [EECE3093C/team-wiitanks-godot-4-networking#7]
Create GitHub issues for required work connected to Unit Testing the code within the Networking repo.
This will include issues for Unit Testing several different classes

Please refer to https://github.com/EECE3093C/team-project-wiitanks/issues/6 for information on how to implement Unit Tests within Godot

**Comment by watermelonslice** [comment]
Created GH-9 and GH-10 to track progress on unit testing. Not looking to spend too much time on tests specific to this repo, just transferrable infrastructure to the core project.
